name: wrf-sensitivity
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - xarray
  - netcdf4
  - metpy
  - wrf-python
  - salib
  - scipy
  - pyyaml
  - tqdm
  - pint