# Record of the u∈[0,1]^10 problem definition (for reproducibility)
names:
  - Tsfc_C
  - Gamma_bdy
  - Gamma_trp
  - Dtrp_km
  - RHsfc
  - Dwv_km
  - Umax_ms
  - Dshear_km
  - curved_shear_per
  - llj_bundle
bounds:  # kept in [0,1]; mapping handled in code
  - [0, 1]
  - [0, 1]
  - [0, 1]
  - [0, 1]
  - [0, 1]
  - [0, 1]
  - [0, 1]
  - [0, 1]
  - [0, 1]
  - [0, 1]
