name: ci
on:
  push: {branches: [main]}
  pull_request:
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - run: pip install -r requirements.txt
      - run: python -m compileall -q src
      - name: Smoke-test generator
        run: |
          python - << 'PY'
          from src.envgen_analytic import generate_sounding, diagnostics
          u = [0.5]*10
          s = generate_sounding(u)
          d = diagnostics(s)
          print(d)
          PY
